import { bhairava, manoj, pramukh, prattush, rudrakh, Kamalesh } from "../assets";

const astrologersData = [
    {
      avatar: manoj, 
      name: "Sri. Manoj Sastri",
      expertise: "Vedic, Numerology",
      languages: "Beng., Eng., Hindi",
      experience: 8, 
      rate: 21, 
      button: "Call Now", 
      rating: 5,
      detail: "Manoj Sastri is a distinguished Vedic and Numerology specialist with a profound expertise spanning over 8 years. Fluent in Bengali, English, and Hindi, Manoj effortlessly connects with a diverse clientele, offering personalized guidance and insights. His in-depth knowledge of Vedic principles and numerology enables him to provide accurate and insightful readings, helping individuals navigate life's challenges and uncover their hidden potential." ,
      chatLink: "https://t.ly/cMnKn",
      phone: "+91 8240060110",
    },
    {
      avatar: pramukh, 
      name: "Pramukh Sastri",
      expertise: "Vastu, Vedic",
      languages: "Beng., Eng., Hindi",
      experience: 7,
      rate: 31,
      button: "Call Now",
      rating: 5,
      detail: "Pramukh Sastri is a renowned Vedic and Vastu specialist, boasting an impressive 7-year tenure in his field of expertise. Proficient in Bengali, English, and Hindi, Pramukh seamlessly caters to a diverse clientele, offering expert consultations and guidance. His comprehensive knowledge of Vedic principles and Vastu Shastra enables him to provide insightful recommendations, helping individuals optimize their living and working spaces to achieve harmony, balance, and prosperity.",
      chatLink: "https://t.ly/cMnKn",
      phone: "+91 7001492922",
    },
    {
      avatar: rudrakh,
      name: "Sri.Rudraksh Sastri",
      expertise: "Life Coach, Numerology",
      languages: "Beng., Eng., Hindi",
      experience: 6,
      rate: 17,
      button: "Call Now",
      rating: 5,
      detail: "Sri Rudraksh Sastri is a highly respected Life Coach and Numerology specialist, with a proven track record of empowering individuals over the past 6 years. Fluent in Bengali, English, and Hindi, Rudraksh effortlessly connects with clients from diverse backgrounds, offering personalized guidance and mentorship. By combining his expertise in numerology with life coaching principles, Rudraksh helps individuals uncover their strengths, overcome obstacles, and achieve their goals, leading to a more fulfilling and purpose-driven life.",
      chatLink: "https://t.ly/cMnKn", 
      phone: "+1122334455", 
    },
    {
        avatar: bhairava, 
        name: "Bhairava Sastri",
        expertise: "Life Coach, Numerology",
        languages: "Beng., Eng., Hindi",
        experience: 6,
        rate: 21,
        button: "Call Now",
        rating: 5,
        chatLink: "https://t.ly/cMnKn",
        phone: "+1122334455", 
      },
      {
        avatar: prattush, 
        name: "Sri.Prattush Sastri",
        expertise: "Life Coach, Numerology",
        languages: "Beng., Eng., Hindi",
        experience: 7,
        rate: 19,
        button: "Call Now",
        rating: 5,
        detail: "Sri Prattush Sastri is a highly acclaimed Life Coach and Numerology specialist, with a remarkable 6-year tenure of guiding individuals toward transformative personal growth. Fluent in Bengali, English, and Hindi, Prattush connects with clients from diverse backgrounds, offering personalized coaching and numerological insights. By combining his expertise in numerology with life coaching principles, Prattush empowers individuals to overcome obstacles, unlock their potential, and achieve their goals, leading to a more purposeful and fulfilling life.",
        chatLink: "https://t.ly/cMnKn", 
        phone: "+1122334455", 
      },
      {
        avatar: Kamalesh, 
        name: "Kamalesh Banerjee",
        expertise: "Nadi, Vastu, Vedic",
        languages: "Beng., Eng., Hindi",
        experience: 9, 
        rate: 27, 
        button: "Call Now", 
        rating: 5,
        detail: "Kamalesh Banerjee is a distinguished expert in Nadi, Vastu, and Vedic sciences, boasting an impressive 9-year tenure of guiding individuals toward harmony and balance in their lives. Proficient in Bengali, English, and Hindi, Kamalesh effortlessly communicates with clients from diverse backgrounds, offering personalized consultations and remedies. With his comprehensive knowledge of ancient Nadi and Vastu principles, combined with Vedic wisdom, Kamalesh helps individuals optimize their living and working spaces, resolve relationship issues, and achieve overall well-being.",
        chatLink: "https://t.ly/cMnKn",
        phone: "+91 8240060110",
      },
  ];
  
  export default astrologersData;
  